### ISSUE TITLE
Move kor.defaults.yml to shared

### ISSUE THREAD

**Issue by bitno** [coneda/kor#103]
Dear @moritzschepp, would it be possible to move kor.defaults.yml to the shared folder, in order to make it resistent to deployments? Or would there be another elegant solution to make the CORS settings persistent? 
Many thanks

**Comment by moritzschepp** [comment]
Hey @bitno, technically that could be done but the file is actually not supposed to be modified, specifically because it is the means by which new configuration options and default values can be introduced. You always make modifications in `config/kor.yml` (the values there override the ones in `config/kor.defaults.yml`) which is symlinked to the shared dir on deployment. Also have a look at https://github.com/coneda/kor#configuration--customizations

**Comment by bitno** [comment]
Understood, very helpful! Many thanks @moritzschepp
