### ISSUE TITLE
Importing relations: log of import, editing relations, checking for duplicates

### ISSUE THREAD

**Issue by bitno** [coneda/kor#106]
Dear @moritzschepp 

On our KOR2 / rechercheportal.gta.arch.ethz.ch we are currently importing loads of data, including relationships. A few questions, that came up during that task:
Is it possible to have the import check, if the exact relation already exists, so that it doesn't get imported another time?
Is it  possible to get a log file, showing what kind of relations went through and which didn't, including error message?
How would one go about editing masses of relations? Is there anything practicable? One use case would be identifying and deleting duplicates.

Many thanks in advance and kind regards,
Leo

**Comment by moritzschepp** [comment]
I assume that you are using a modification of the `custom.example` script:

You may check if a relation exists already by using a select on the `Relation` model à la (e.g.):

    if r = Relation.find_by(name: "is sibling of")
      # handle the case when it exists
    else
      # handle the case where it doesn't exist
    end

within the first block of the `if` statement, you may also express other conditions on the `r` object if you'd like to allow duplicate relations but only (e.g.) between different sets of kinds.

At any time, you can insert log statements to get an idea what happened:

    new_relation = Relation.new(...)
    unless new_relation.save
      STDERR.puts "didn't create relation #{new_relation.inspect}"
    end

For finding duplicates, an option is to use the SQL group by clause (via activerecord):

    Relation.group(:name).count.each do |name, count|
      if count > 1
        puts "relation '#{name}' exists #{count} times"
      end
    end

**Comment by bitno** [comment]
Dear @moritzschepp 
Yes, I meant custom.example and many thanks for these very useful answers as well als those in #107 . 
How does this behave, when looking at relationships of one particular relation type? 
Meaning finding all duplicates of relationships between the same two entities and deleting them?
A is sibling of B
A is sibling of B
A is sibling of B

where I want to end up with just
A is sibling of B.

And is there a way to export/import all relations similar to entities? 

Many many thanks and lots of greetings,
Leo

**Comment by moritzschepp** [comment]
For relationships, its essentially the same mechanism but the recently introducted "directed relationships" should facilitate the task:

    DirectedRelationship.group(:from_id, :relation_name, :to_id).having("count(*) > 1").count.each do |criteria, c|
      fid, rn, tid = criteria
      relationships = DirectedRelationship.where(from_id: fi, relation_name: rn, to_id: tid).map{|dr| dr.relationship}
      # and here you can decide which of the relationships to drop, e.g. all but the first:
      relationships[1..-1].each{|r| r.destroy}
    end

Be aware that you can't add the properties to the `group` clause since they are serialized into a text field and therefore not reliably comparable. If you'd like to delete relationships based on their properites, you'd have to do the selection wihin the loop.

I'm not sure I understand the question "And is there a way to export/import all relations similar to entities?" What "way" for entities are you referring to?

**Comment by bitno** [comment]
Dear @moritzschepp ,
Many thanks, it worked great and solved our issue. One small typo in line 2, it should be fi and not fid, should you wish to copy this to the example script.
One other question in this thread was the issue of a useful log. How and where in a script would I add this? The idea would be to get a text file / log file containing all successfull database actions, like write, delete, destroy, etc. When loading thousands of fields and relations, this would enable the user to check his progress, ie quality of the import.
Many thanks once again and lots of greetings,
Leo

**Comment by moritzschepp** [comment]
Yes that's a good idea to put the above code into the example script. I'll do that, including a way to have some logs. To help you out right away, this is how you could do it: Since all SQL is effected by ActiveRecord, you may just redirect its log (which normally goes to log/production.log). Add one of the following after the rails environment is loaded in the script:

    # to just print the log messages to the current terminal
    ActiveRecord::Base.logger = Logger.new(STDOUT)

    # to write messages to a file
    ActiveRecord::Base.logger = Logger.new(File.open '/path/to/some/file.log')
