### ISSUE TITLE
information request: video handling

### ISSUE THREAD

**Issue by bitno** [coneda/kor#122]
Dear @moritzschepp 
I would just like to know, what kind of video conversion options, if any, are currently available in KOR? Streaming large videos seems to be an issue with one of our custom built frontends, that's why the question arose.
Many thanks for the clarification and lots of greetings

**Comment by moritzschepp** [comment]
... so I did some digging with the video you referred to in your emails:

on my laptop, the following run fine, which are the commands run by KOR (see also https://github.com/coneda/kor/blob/master/lib/paperclip_processors/video.rb), except for the time option to only encode one minute:

    ffmpeg -t 00:01:00 -i 4529.original.mov -c:v libx264 -crf 28 -c:a aac -b:a 256k -strict experimental out.mp4
    ffmpeg -t 00:01:00 -i 4529.original.mov -c:v libvpx -crf 10 -b:v 1M -c:a libvorbis -qscale:a 7 out.webm
    ffmpeg -t 00:01:00 -i 4529.original.mov -c:v libtheora -qscale:v 7 -c:a libvorbis -qscale:a 7 out.ogv

and the resulting videos play fine with mplayer. However, this conversion alone takes about 20 minutes per format, which is mainly due to the fact that the resolution is 2880x1800 (!). So I extracted 15 seconds to test with KOR:

    ffmpeg -t 00:00:15 -i 4529.original.mov -c:v copy -c:a copy short.mov

and then I uploaded that in KOR. After 20 Minutes, I opened the page in the default backend and the movie seems to play without problems. Its worth saying that I also got 500 from the API before the conversion was complete for all three formats.

Perhaps you want to test the ffmpeg commands on your server? Also, the delayed_jobs table in mysql should tell you about conversion jobs that havn't finished (yet) and why. You can access it with Delayed::Job from the console. For docs, please refer to http://guides.rubyonrails.org/v4.2/active_record_basics.html

To reprocess a medium, please run (replace document with image to recreate image thumbnails):

    Entity.find(1234).medium.document.reprocess!

BTW, for ffmpeg vs avconv, I found this:
https://stackoverflow.com/questions/9477115/what-are-the-differences-and-similarities-between-ffmpeg-libav-and-avconv

**Comment by moritzschepp** [comment]
@bitno, can this be closed?

**Comment by bitno** [comment]
Dear @moritzschepp 
I guess so, in case it pop's up again it will be a more specific question. Btw, are you back from your holidays?
Regards
