### ISSUE TITLE
Bug: Publishing of groups

### ISSUE THREAD

**Issue by Diederka** [coneda/kor#124]
Publishing of groups seems not to function. 
I test published a group called Offentest. Conedakor generated a link and an expiration date. But without login, the pictures cannot be watched just by using the link. 
Here is the testlink: 
https://testing-maya.coneda.net/pub/1/3ea29bf6bd9a expiration date: 22.08.2017 10:04

**Comment by wuebbena** [comment]
Maybe there is a problem with the authority. IMHO you should allow „guest“ to see the images of the relevant collection. But maybe I'm barking up the wrong tree, What do you think @moritzschepp ?

**Comment by Diederka** [comment]
But I thought i did so: 
See Screenshots: 
https://drive.google.com/open?id=0BybRflNasKqLM3hDVkF1Sk02aFE
https://drive.google.com/file/d/0BybRflNasKqLdWVpM1hqZEM1cW8/view?usp=sharing

**Comment by wuebbena** [comment]
I think I solved it. There was no user “guest“ and that was the whole problem. 
Under https://testing-maya.coneda.net/pub/1/3ea29bf6bd9a you can see now the image  https://testing-maya.coneda.net/blaze#/entities/748 because it is in the collection "Gästetagsammlung" which is open. https://testing-maya.coneda.net/blaze#/entities/746 is still in the collection "Default" which is not open for "guest".

**Comment by Diederka** [comment]
Thanks!

**Comment by moritzschepp** [comment]
After discussing it a bit, we determined that this is actually a bug. The image should be shown (the entity is already visible but the picture is missing) ... reopening.
