### ISSUE TITLE
deleting data from particular field in dataset

### ISSUE THREAD

**Issue by bitno** [coneda/kor#133]
Dear @moritzschepp 
As promised, I keep them tickets coming today. I promise to write all of this up and send over, so that you can upload it on github for future reference.

I want to deleted all the content from one particular field in the dataset. 
How can this be done through a script?
How can this be done through ruby?
What would be the best way to do this?

```

default = Collection.where(:name => 'default').first
document = Kind.where(:name => 'Dokument').first

	document.entities.each do |document_entity| 
  document_entity.dataset['dokument_bildnachweis'] = []
```
How can one iterate through all entities of one particular entity type?
What is the syntax to set the value of a particular field to null ("", [], null, empty)? Or would **destroy** also work on this?

Many thanks and kind regards,
Leo

**Comment by moritzschepp** [comment]
The current master should manage the dataset fields automatically, so:

* if you rename a field (kind editor) then all entities will migrate to the the field name
* if you remove a field (kind editor), then all entities will lose that dataset value

This "synchronization" is time consuming, though, which is why we run it as a background job. It gets queued for the `delayed_job` as for example the image conversions.

However, if you want to do it with a script then this will remove a value from the dataset:

    document_entity.dataset.delete['dokument_bildnachweis']

This is just plain old ruby (removing a key from a hash).

**Comment by bitno** [comment]
Gracias!!! Will test asap.
