### ISSUE TITLE
background process not working properly and issue with media permissions

### ISSUE THREAD

**Issue by bitno** [coneda/kor#143]
Dear @moritzschepp 
Somehow my background process on https://conedakor5.ethz.ch/ is not working correctly. 
I uploaded a jpg (https://conedakor5.ethz.ch/blaze#/entities/460550) and a tif (https://conedakor5.ethz.ch/blaze#/entities/460551), but they are not being processed, even though the background process is working.

On top of that, there seems to be another issue. I can't rotate my media.
I get an error each time I try to do that. The log shows, that the requested file is not available, which indeed seems to be the case. Do you happen to have an idea, why this is the case?

The log: 
[log20171115_v5.log](https://github.com/coneda/kor/files/1474666/log20171115_v5.log)

Many thanks in advance

**Comment by moritzschepp** [comment]
Yes, this happens if the background process or the web app itself have been running as `root`. After that, if it is run as a different user, typically `www-data`, the process has no permissions to change/delete the previously created files. Your log file shows the permissions error. If you fix the permissions and ownership within your data directory, both problems will go away.

**Comment by bitno** [comment]
Many thanks as always, this worked out well:

`chown -R kor. /var/www/rack/kor/shared/data`

I later found, that something similar was discussed in ticket #102 just as a reference.
