### ISSUE TITLE
outdated link to source code of verison 2.1.0

### ISSUE THREAD

**Issue by Diederka** [coneda/kor#145]
The following link (provided on our login-website https://classicmayan.kor.de.dariah.eu/login)
is outdated:  
https://github.com/coneda/kor/releases/tag/2.1.0

**Comment by wuebbena** [comment]
Indeed, the correct link is: https://github.com/coneda/kor/releases/tag/v2.1.0

**Comment by moritzschepp** [comment]
The problem is fixed in the current master. If you'd like to fix it without updating, make sure the file `config/kor.defaults.yml` points to the correct link template, so replace

    ...
    sources:
      release: "https://github.com/coneda/kor/releases/tag/{{version}}"
    ...

with

    ...
    sources:
      release: "https://github.com/coneda/kor/releases/tag/v{{version}}"
    ...

You can also override this valie in `config/kor.yml`, remember to remove the override there or to use the same value.
