### ISSUE TITLE
generator Field which is set "not be visible" on entity page is visible though 

### ISSUE THREAD

**Issue by Diederka** [coneda/kor#147]
In the Field administration for the entity Person the field "VIAF_File" which has also a generator, should only be shown, when it is filled. Thus I didn't set it "Visible on entity page".  
https://classicmayan.kor.de.dariah.eu/kinds/4/fields/25/edit
But when an entity Person is created, the field is shown, though not filled , see example: 
https://classicmayan.kor.de.dariah.eu/blaze#/entities/995
Other fields which are not set visible, stay invisible. 
Is there something wrong with the code?

**Comment by wuebbena** [comment]
I don't have the permission do have a look behind the scenes and due to this I'm not able to follow the link https://classicmayan.kor.de.dariah.eu/kinds/4/fields/25/edit.
But I can show you the configuration of https://kor.uni-frankfurt.de (v2.1.0) where it does :

Generator
- Name: viaf_p214
- Generator directive: <a ng-if="entity.dataset.p214" href='https://viaf.org/viaf/{{entity.dataset.p214}}' target='_blank'>» VIAF</a>

IMHO you should have a close look at the "ng-if"-part of this.

**Comment by Diederka** [comment]
the directive was ok. I used the following: 
<span ng-if="entity.dataset.gnd_id">
  <a href="https://viaf.org/viaf/{{entity.dataset.viaf_file}}">
    Virtual International Authority File (VIAF)
  </a>
</span>
So the link works, if the field is filled. 
but the visibility was the problem, if the field was not filled. 
But never mind. 
I will try to fill it always otherwise i will restrict to only gnd-links. 
Thank you!

**Comment by Diederka** [comment]
Ah, now I read your comment about the if part... Thank you!
