### ISSUE TITLE
oaipmh xml doc not valid

### ISSUE THREAD

**Issue by S-Peter** [coneda/kor#16]
I get the following errors when validating the ListRecords-XML doc for repo .../api/oai_pmh/kinds.xml against the aoipmh schema:

Element '{http://www.openarchives.org/OAI/2.0/}request', attribute 'verb': [facet 'enumeration'] The value 'ListRecord' is not an element of the set {'Identify', 'ListMetadataFormats', 'ListSets', 'GetRecord', 'ListIdentifiers', 'ListRecords'}.
Element '{http://www.openarchives.org/OAI/2.0/}request', attribute 'verb': 'ListRecord' is not a valid value of the atomic type '{http://www.openarchives.org/OAI/2.0/}verbType'.
Element '{http://www.openarchives.org/OAI/2.0/oai_dc/}dc': No matching global element declaration available, but demanded by the strict wildcard.
Element '{http://www.openarchives.org/OAI/2.0/oai_dc/}dc': No matching global element declaration available, but demanded by the strict wildcard.
Element '{http://www.openarchives.org/OAI/2.0/oai_dc/}dc': No matching global element declaration available, but demanded by the strict wildcard.
Element '{http://www.openarchives.org/OAI/2.0/oai_dc/}dc': No matching global element declaration available, but demanded by the strict wildcard.
Element '{http://www.openarchives.org/OAI/2.0/oai_dc/}dc': No matching global element declaration available, but demanded by the strict wildcard.
Element '{http://www.openarchives.org/OAI/2.0/oai_dc/}dc': No matching global element declaration available, but demanded by the strict wildcard.
Element '{http://www.openarchives.org/OAI/2.0/oai_dc/}dc': No matching global element declaration available, but demanded by the strict wildcard.
Element '{http://www.openarchives.org/OAI/2.0/oai_dc/}dc': No matching global element declaration available, but demanded by the strict wildcard.
Element '{http://www.openarchives.org/OAI/2.0/oai_dc/}dc': No matching global element declaration available, but demanded by the strict wildcard.
Element '{http://www.openarchives.org/OAI/2.0/oai_dc/}dc': No matching global element declaration available, but demanded by the strict wildcard.

**Comment by moritzschepp** [comment]
Ok this is messy business. I asked on nokogiri groups because it doesn't validate how I'd expect. See the thread there at
https://groups.google.com/forum/#!topic/nokogiri-talk/svRHxSxZiwc

and the referenced message from a mailing list at
https://mail.gnome.org/archives/xml/2009-November/msg00022.html

I managed to make our tests pass by constructing the suggested dummy schema. This is not very pretty but it works. Have a look at (e.g.)
spec/controllers/api/oai_pmh/kinds_controller_spec.rb:86

on how to validate the XML with nokogiri in this case.

Other than that, there have been problems within the XML that I hoped I fixed. This also required to declare the content of `<dc:description>` as CDATA. This is also why parsing got slightly more difficult, see:
spec/controllers/api/oai_pmh/kinds_controller_spec.rb:72
