### ISSUE TITLE
Insconsistent using of upper and lower case  writing for titles in the kor frontend

### ISSUE THREAD

**Issue by Diederka** [coneda/kor#168]
**_Should this be a pull request for the code?_** 
The Frontend lacks of consistent using of upper and lower case  writing for titles. 
E.g. at the left you alwas have a site list, a list of sites to go to. 
I copied the text into here, it is written as followed: 
Edit profile
Clipboard
New entries
Simple search
Expert search
Groups

    Multiple upload
    Invalid entities
    New entities
    Isolated entities
    Administration
        General
        Relations
        Entity types
        Collections
        User groups
        User administration
    Statistics
    Error report
    help
    Terms of use
    Imprint
    coneda.net
    Report a problem"

Everything is written Uppercase instead of "help" which is written lowe case. 
Also Titles with more than one word are written inconsistent. E.g.: "Terms of use". 
Can you change that? 
When the database will be available through the dariah webservice, it won't look too good, if it has inconsistencies.

**Comment by moritzschepp** [comment]
Thanks for spotting this. I will change the help button accordingly. The problem with capitalization is that there is not really "right" and "wrong" as far as I can see. E.g. Microsoft shows the different options [here](https://msdn.microsoft.com/en-us/library/windows/desktop/bb246428(v=vs.85).aspx) and they suggest title case for navigational elements. There are other style guides available. Here or some from the scientific publishing world: https://english.stackexchange.com/a/6573/14662

So I'm unsure how to proceed. Until now, we used sentence case for everything. This has also the advantage that we don't need to maintain two translations like "invalid entities" and "Invalid Entities" depending on context.

That said, I have no preference but I think we should handle it consistently. What's your take on this, @wuebbena?

**Comment by moritzschepp** [comment]
I just checked and we already fixed the help capitalization in #146

**Comment by Diederka** [comment]
@moritzschepp : I agree with you "but I think we should handle it consistently". I have no preference though .

**Comment by wuebbena** [comment]
Sorry, I didn't see that.
Yes we "should handle it consistently" but nevertheless we need a decision here. :-) Let's give it a try. In my opinion it would be an advantage to work with upper-case characters because all the solitary words like "help", "original", "enlargement", "maximize" etc. would benefit from this approach. And the combined words like "Isolated entities", "Terms of use" etc. would also work in full capitalization – also in whole sentences, since they are to be regarded as a kind of proper noun within the KOR app. What do you think?

**Comment by Diederka** [comment]
I agree. I also prefer capitalization. but capitalization at the beginning of each word was my preference here. i never thought of more. but full capitalization could help making clear that these are kor elements/functions.

**Comment by Diederka** [comment]
If it’s my choice, I would prefer 2.

**Comment by wuebbena** [comment]
I was still a little undecided, but if it can be kept clean: it's number two.

**Comment by moritzschepp** [comment]
Ok you prefer 2. This is how its currently implemented. Is the app not conforming to that in any way?

**Comment by wuebbena** [comment]
The following expressions deviate from this rule.: 
coneda.net“, “terms", "tags", "search", "search results", "entities", "usage count", "name", "description", "personal collection", "username", "full name", "e-mail", "created at", "last login", "expires at", "user", "logged in recently", "logged in within the last year", "created recently", "links", "session".

**Comment by moritzschepp** [comment]
These seem to be all column headers for tables, not page headers or menu items. Should I apply the rule to them as well?

**Comment by moritzschepp** [comment]
The menu you sent when opening this issue seems fine except "help", which was corrected in #146. There is also "coneda.net" which is a bit of a special case simply because its very unusual to have capital letters in domain names) but I'm happy to change it if everyone prefers.

Other than that, changed: 
* the "Edit profile" page header
* the "Simple search" page and result headers as well as terms and tags fields
* the "Expert search" page header
* "Type of dating" and "Dating" when adding dating information to entities
* "Search" above the user list

The other ones are all table headers, no? How shall I proceed there?

**Comment by Diederka** [comment]
Yes, thanks, "help" was the most obvious flaw. 
And I also think "coneda.net" can stay unchanged.

**Comment by moritzschepp** [comment]
@wuebbena ?

**Comment by moritzschepp** [comment]
And what about the table column headers? Should I use sentence case there as well?

**Comment by wuebbena** [comment]
I would prefer it. Are there difficulties that I don't see now?

**Comment by moritzschepp** [comment]
No difficulties, I assumed that you want it that way ... but you also said that you are happy with the current situation .. that's why I asked.
