### ISSUE TITLE
"bundle exec rake jobs:work" doesn' stop

### ISSUE THREAD

**Issue by MaximilianBrodhun** [coneda/kor#188]
We have a problem regarding the command "bundle exec rake jobs:work". 

All mediums were deleted but by the execution of the given command the job runs and doesn't end. The output for each job is:

`[Worker(host:classicmayan pid:15929)] Job ActiveJob::QueueAdapters::DelayedJobAdapter::JobWrapper (id=67058) (queue=paperclip) RUNNING
[Worker(host:classicmayan pid:15929)] Job ActiveJob::QueueAdapters::DelayedJobAdapter::JobWrapper (id=67058) (queue=paperclip) FAILED (3 prior attempts) with ActiveRecord::RecordNotFound: Couldn't find Medium with 'id'=33490`

**Comment by moritzschepp** [comment]
It seems like a job is still left from before deleting the images. You can empty the job queue in the console with `Delayed::Job.destroy_all`. In any case, jobs:work is starting a worker that will wait for new jobs to come in. Its not supposed to terminate. If you'd like instead to just work off the available jobs and then exit, use jobs:workoff instead.

**Comment by MaximilianBrodhun** [comment]
A few seconds ago I found this also but was not sure if it is correct.

But thanks alot. I will try!

**Comment by Diederka** [comment]
Danke, dass du dich drum kümmerst.
Wenn es heute nicht mehr ganz kklappt... Bin dann bis Monatg weg und werde 
Dienstag wieder arbeiten. Mal hoffen, ob bis dahin alles okay ist.
Viele Grüße Katja


____________________________

Katja Diederichs

"Textdatenbank und Wörterbuch des Klassischen Maya"
Arbeitsstelle der NRW Akademie der
Wissenschaften und der Künste
Universität Bonn
Abteilung für Altamerikanistik
Oxfordstraße 15
53111 Bonn

katja.diederichs@uni-bonn.de
+49 228 73 62307
http://www.mayawoerterbuch.de

On Thu, 02 Aug 2018 04:31:39 -0700
  MaximilianBrodhun <notifications@github.com> wrote:
  A few seconds ago I found this also but was not sure if
it is correct.

  But thanks alot. I will try!

  --
  You are receiving this because you are subscribed to this
thread.

**Comment by wuebbena** [comment]
@MaximilianBrodhun Can it be closed?
