### ISSUE TITLE
Media Search

### ISSUE THREAD

**Issue by Diederka** [coneda/kor#200]
Media cannot be searched directly by title or properties or relationships. 
However  if I search for the medium name (in simple search) I won't find the medium itself but you will find the entities (artefact, place, collection) related to it. 
Why is that? 
And why can't media be searched directly at all?

**Comment by wuebbena** [comment]
How would you like to search for a medium? Because in most of our cases - no, actually always - the medium has no title, but characteristics (as a digital representation mostly technical or as a representative of the physical thing only in connection with other entities). One of these characteristics is the link to a work of art, for example. This is due to the strict separation between the concept, which can be presented in different media, and why it would be wrong with this procedure if the medium would carry the title. For example, we only have the concept "Cologne Cathedral" once, but there are dozens of images (media) that show, among other things, the different views, building conditions, etc.. But maybe @moritzschepp can explain this even better.
But it would be interesting to search for media with certain rights and that's one of the reasons why we just created Ticket #199 .

**Comment by Diederka** [comment]
You are right. 
The metadata concept and modeling with entities and relationships (as relation-based characterization of the metadata) is also used by us. 
And I think I put it wrongly in my question.  
I want to be able to search for certain image files - not so much for the entity medium... 
For example, we were quoted. 
 And there the file name of the original file was specified correctly: KHM_1978_F51_R06_33 (as name of the original archival record). 
But we can't find it in the database, only indirectly - as I described. 
On the other hand we can enter your UUID of the medium and find it (but this UUID is the identifier of the database - not that of the original archive), the identifier of the archive can be found under the medium property "Image Number".

**Comment by moritzschepp** [comment]
@wuebbena, no there is nothing to add :+1: 

@Diederka, in your specific case, your field "image_no", which is rendered as "Image Number" contains the archival record id and this field was specified as an identifier when it was created on the medium entity type. In KOR, identifiers can be "resolved" with `/resolve/<field>/<identifier>`. For example, to reference the medium with `image_no=KHM_1978_F51_R06_33`, you can simply write https://classicmayan.kor.de.dariah.eu/resolve/image_no/KHM_1978_F51_R06_33, this then redirects to https://classicmayan.kor.de.dariah.eu/blaze#/entities/81483

If I got it right, the above solves your problem (does it?).

For media entities as search results, there is also the ticket #135.

**Comment by Diederka** [comment]
@Schepp: That is excellent! I used the identifiers but dint't really know how or where that should be useful. But that will solve my problem. I only will have to write it into our search help documentation.

**Comment by wuebbena** [comment]
I'm not sure. But a ticket without an assignee is a little bit scary - in my eyes. :-) The question is, is there anything left to do here?

**Comment by moritzschepp** [comment]
I wouldn't know, @Diederka should we close here?

**Comment by Diederka** [comment]
sorry, you are right. Pleas close!
