### ISSUE TITLE
Question: how can the given names (or distinct name) fields of entities be used as identifiers?

### ISSUE THREAD

**Issue by Diederka** [coneda/kor#202]
You told me last time "In KOR, identifiers can be "resolved" which I find very useful to construct something like permanent uris (corresponding semantically to the information given). 
This way coukd be referencable. 
But unfortunately I only can use the possibility of resolving the identifiers of media in our database. 
It is not possible to use them for our entity types "collection", "holder", "place" "person", artefact", "provenance". Because in our data model we understand the names (sometimes distinct names) of our entities as their identifier, which is also find quite intuitive. But to use the name/distinct name fields as identifier is technically not possible in kor (at least not for the admin via browser/frontend). 
Here KOR does only allow to use identifiers for dataset fields (fields created by the admin for the matadata schema). 
Question: is it possible to make me (the admin) use identifiers for default fields like name to be able to permantntly reference e.g. an Artefact with the given field name: "Yaxchilan Stela 1"? so the URI would look something like: https://classicmayan.kor.de.dariah.eu/resolve/Artefact.Name/Yaxchilan+Stela+1 or something like that?

**Comment by moritzschepp** [comment]
Yes, we could add a resolving mechanism as you suggest relatively easily. Consider the implications, though: The entity's name and distinct name are (together) unique. But as soon as they change, so would the resolve url. For example, if you discover in a year that "Yaxchilan" should actually be spelled "Jaxchilan", the previous urls wouldn't work anymore.

Alternatively and to prevent this problem, you could add an identifier field and copy the name there, so that it could stay the same even if the entity's name changes.

**Comment by Diederka** [comment]
You have a point. That' s problematic in terms of data consistency.. 
Okay, I have to think of something here for our use case and I will use a self made dataset field.
