### ISSUE TITLE
include entity dataset in mirador manifest

### ISSUE THREAD

**Issue by Diederka** [coneda/kor#207]
I have a question about the nice implementation of the Mirador viewer. 
i think it's great that the pictures can be viewed with a click in the Mirador Viewer and can be compared with other pictures, etc. 
But my problem: 
Our important metadata like 
"Rights statement" (license) 
"Description" and "image name" (in our own domain-specific metadata definitions of course) are not displayed in the Mirador metadata. 
See screenshot. 
![screenshot 2019-02-13 17 06 52](https://user-images.githubusercontent.com/25532142/52727105-d115db00-2fb4-11e9-99b5-36e34ce3eefc.png)

Of course mirador doesn't read this metadata, 
but also we wouldn't know the rule which fields to use..  
Mirador follows the IIIF standard, doesn't it? 
My question: 
What do we have to do for Mirador to read and use or map our three most important metadata information? 
Namely:  
Label - that would be our field: Image number
Rights - that would be our field: License 
Description: that would be our field: Description
And another question: 
What's the JSON string that's listed as a link? 
Where did Mirador generate that from?

**Comment by moritzschepp** [comment]
I'm happy you like the viewer integration!

Basically, label and description are empty because there is no domain-independent way of determining the right values to use. But mirador also allows an arbitrary amount of additional metadata (like the filename). We could show the dataset values the same way. Be aware that showing generator values won't be possible for now, since that is generated in the web interface for now. Would that work?

The JSON url is the image's ID: Mirador loads this url to get the information about this image. You can load it yourself in a browser which also shows the current metadata composition. You may want to install https://chrome.google.com/webstore/detail/jsonview/chklaanhfefbnpoihckbnefhakgolnmc if you're using chrome.

**Comment by Diederka** [comment]
That would be great!
Okay, but the dataset field "license" as some others uses a generator. But I understand that if I delete the generator for that fields, the content of e.g. "license" (which is always "CC BY 4.0") can be read.  Think for that reason and apart from the generator for IMAGE NUMBER (which is set as Identitifer and uses the resolver to lead to our permalink of the image entity), all generators can be deleted here. 
so, if i delete them now could the filled dataset be displayed? 
And how? Can you do that?

**Comment by moritzschepp** [comment]
Sorry I wasn't clear about this: The generators can simple not be shown for the moment, because they run in the browser and it would require some more work to integrate them with mirador. The dataset values can be shown without problem. No need to remove the generators.

I will implement this for v3.1 and if you like, you can copy a small snippet into your Installation to make it work without upgrading. I'll update this ticket with the relevant code.

**Comment by Diederka** [comment]
Oh that 's great! So i can stick with the generators. 
Thanks, i would like to use that snippet from v 3.1.

**Comment by moritzschepp** [comment]
In the meantime, we got a feature for complete customization of the manifest (#302) which also allows adding the dataset. Closing.
