### ISSUE TITLE
question: a template, which would be filled once and remains for all further inputs. 

### ISSUE THREAD

**Issue by Diederka** [coneda/kor#231]
This is a question of a user / editor to me, which I ask here: 
Is it possible to leave certain fields prefilled in a kind of template when creating an image medium? 
For example, when uploading about 5, sometimes 20 or more images from external museums like the MET Museum, we have to fill in certain fields that should always have the same values,  
such as 
https://classicmayan.kor.de.dariah.eu/blaze#/entities/17764 
here we have fields like these, which are the same for every medium of that specific collection. 

License: CC0 1.0
Creator: Metropolitan Museum of Art
Digitized by: Metropolitan Museum of Art
Contributor: Project Text Database and Dictionary of Classic Mayan
Rights Holder: Metropolitan Museum of Art
Publisher: Maya Image Archive

It would be nice for the users if a template, which would be filled once, could remain for all further inputs. 
This template should then be created once again for the next museum entries and reused. 

PS: The fields Contributor and Publisher are ALWAYS filled with the same Values in our Database.

**Comment by moritzschepp** [comment]
I think I understand, sounds like a good feature. There are two separate parts to this, I believe:

1) The entity form could be adapted to allow presetting field values. In fact, this is already done with the kind_id in e.g. `/entities/new?kind_id=2`. This could be extended to allow other fields to be set in this way.

2) If you have fields that really always have the same value, why do you want to add the data to KOR at all? Could that not be added to the general description of the database, then?

**Comment by Diederka** [comment]
To 1: 
I coudn't resolve this uri https://classicmayan.kor.de.dariah.eu/entities/new?kind_id=2. Or what was it from? And what is it about?

To 2: 
If they always had the same value, you were right. And in the ruby scripts for mass importing our images from Karl Herbert Mayer I have set some values with static content 
like: 
`\"contributor\" : \"Project Text Database and Dictionary of Classic Mayan\",
\"rights_holder\" : \"Karl Herbert Mayer\",
\"publisher\" : \"Maya Image Archive\",
\"digitized_by\" : \"Project Text Database and Dictionary of Classic Mayan\",
`
But it is about fields from a medium, where editors upload license free media from other databases manually via browser and describe them.
The aforementioned template, which would be filled once, could remain for all further inputs would be ideal there. 
Maybe you referred to this in 1) but I cannot resolve this URL.

**Comment by moritzschepp** [comment]
1. If you bring up the form to create a new entity (non-medium), you can see a similar url which basically presets the kind in the form. So we could implement it in a way that this could also be done with other fields like `name` or even dataset fields. It might be that my specific url doesn't work for you because you have no kind_id=2.
2. Ok so if they are not always the same then you could use the mechanism proposed in 1., no?

**Comment by Diederka** [comment]
I think your proposition 1. seems to be the right one if it works with urls for data fields. 
But how can you do this url-thing? 
if for example the data fields 
\"contributor\" , \"publisher\"  \"digitized_by\" 
should be flexible and have to change for every new import with around 100-1000 images
will you establish that in a new version?

**Comment by moritzschepp** [comment]
The way this could work is that you use a specific url, e.g.

https://kor.example.com/#/entities/new?kind_id=4&dataset[digitized_by]=1234

And this would show the form with the field "digitized_by" prefilled with 1234. I think we wouln't add a specific button for those because they are specific to the use-case but you could use them with browser bookmarks. Could that work?

**Comment by Diederka** [comment]
okay, possible solution. But I tried it and it didn't work. But maybe because of the problem with kor at the moment. I'll keep it in mind.

**Comment by moritzschepp** [comment]
Oh no, this doesn't work yet, its just a suggestion on how it COULD work.

**Comment by Diederka** [comment]
Okay, that could be a solution we would use. And it would be even better, if there were the possibility for many fields to be filled at once for one new entity.

**Comment by moritzschepp** [comment]
I am working on this at the moment and the url approach is perhaps less convenient than I thought, because it wouldn't be straight forward to express complex values (datings, synonyms etc.) in the url string.

I was thinking that a good alternative could be to have a "clone" button on every entity which would open a "create" form but with all values prefilled according to the cloned entity. This way, you could have a template entity from which you can make quick copies. We could then also add a configuration option to use this cloning for all newly created entities. What do you think?

**Comment by Diederka** [comment]
Yes, I think this proposed cloning Button is a good solution. 
It would save a lot of typing work when creating new entities, especially media entities.
