### ISSUE TITLE
Usage of oai-pmh harvesting script

### ISSUE THREAD

**Issue by MaximilianBrodhun** [coneda/kor#245]
I want to use the script oai_pmh_client script to harvest the repo.

But I get several errors.

Af first: the usage of https in the field "url" will be proceed with the error message:

`2019-04-30 11:55:12 SSL_connect returned=1 errno=0 state=error: certificate verify failed`

If I change this field to "http" I will get the following error message.

```
2019-04-30 11:58:05 ERROR: Undefined namespace prefix: //xmlns:error/@code
/usr/local/rvm/gems/ruby-2.4.1/gems/nokogiri-1.8.2/lib/nokogiri/xml/searchable.rb:198:in `evaluate'
/usr/local/rvm/gems/ruby-2.4.1/gems/nokogiri-1.8.2/lib/nokogiri/xml/searchable.rb:198:in `xpath_impl'
/usr/local/rvm/gems/ruby-2.4.1/gems/nokogiri-1.8.2/lib/nokogiri/xml/searchable.rb:179:in `xpath_internal'
/usr/local/rvm/gems/ruby-2.4.1/gems/nokogiri-1.8.2/lib/nokogiri/xml/searchable.rb:154:in `xpath'
oai_pmh_client:53:in `block in fetch'
oai_pmh_client:46:in `loop'
oai_pmh_client:46:in `fetch'
oai_pmh_client:32:in `run'
oai_pmh_client:185:in `<main>'
doc:
<?xml version="1.0"?>
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN" "">
<html>
  <head>
<title>301 Moved Permanently</title>
</head>
  <body>
<h1>Moved Permanently</h1>
<p>The document has moved <a href="https://classicmayan.kor.de.dariah.euapi/oai-pmh/kinds.xml?metadataPrefix=kor&amp;api_key=e7d503f787d9623213b505c8004f0945f6b246ee85f954b8d0ace6f136bfac7260980a2b2269259bd9a7b7d086eccde2&amp;verb=ListRecords">here</a>.</p>
</body>
</html>
```

The request is not handled correctly and so the namespace error is throwed.
In the href attribute the url is: "https://classicmayan.kor.de.dariah.euapi/oai-pmh/kinds.xml?" so the slash before the "api" is missing. Is the problem above.

It try to add a slash in the field "url" but nothing has changed:

My setting are:

```
Kor::OaiPmhClient.new(
  url: 'http://classicmayan.kor.de.dariah.eu/',
  api_key: '*******************',
  target_dir: './kor_xml',
  continue: false
).run

```

**Comment by moritzschepp** [comment]
You are getting `certificate verify failed` because the ssl setup for https://classicmayan.kor.de.dariah.eu is incomplete. Most likely, an intermediate certificate is missing. This makes it work for most desktop browsers (because they ship the intermediate) but not for simpler clients, e.g. curl or http libs. Have a look at https://www.ssllabs.com/ssltest/analyze.html?d=classicmayan.kor.de.dariah.eu for more details.

The non-https version of the url leads to a redirect to the respective https version of that page. That's good practice but the redirect should be done correctly.

Both problems can only be corrected in your apache config. Let me know if you need more details.

You can try with

~~~ruby
Kor::OaiPmhClient.new(
  url: 'https://testing-4.coneda.net',
  api_key: '',
  target_dir: './kor_xml',
  continue: false
).run
~~~

to see if your script is set up correctly. Make sure to remove the /api prefix from the url in line 51 because the url changed, so it should look like this: `doc = oaipmh("/oai-pmh/#{type}.xml", params)`.
