### ISSUE TITLE
REST JSON-API: Problems with results above 10.000?

### ISSUE THREAD

**Issue by MaximilianBrodhun** [coneda/kor#353]
I tried to get all entities of a specific kind_id and do this with the parameters per_page and page.

The total amount of entities is near 13000. I tired per_page=100 and untill page=100 everything is fine. But above pagenumber 100 no results will be returned. But instead 

```
{"status":500,"error":"Internal Server Error"}
```

If I set per_page to 1 and page to 10000 everything is fine, but page=10001.

So it seems to me that there is a problems to get elements more than 10000.

**Comment by moritzschepp** [comment]
Yes, you are right. I checked on your host and the elasticsearch instance wasn't configured to return a large enough "result window". I changed the setting from 10k to 50k and it works now.

I'll keep this issue around as an enhancement, because I'd like to have kor change the setting when the index is created.

**Comment by MaximilianBrodhun** [comment]
Thanks alot, works fine.
