### ISSUE TITLE
enhancing new relationship functionality by dynamically filtering relationship types

### ISSUE THREAD

**Issue by bitno** [coneda/kor#42]
starting point: The user is on a specific entity and is trying to add a new relationship with the new functionality in v2.0. 
steps taken: The user selects a target entity from one of the three possible tabs (search, last visited, last created), before choosing a relationship type. 
problem: Now the dropdown menu is still showing all relationships and is not dynamically reducing them to the ones possible for the two entities chosen. 
reasoning: this addition would help databases with large amounts of relationship types, as the non relevant and not usable relationship types would not even be shown as an option.

**Comment by moritzschepp** [comment]
Thanks again!

**Comment by moritzschepp** [comment]
I was thinking about this feature again and I was wondering: We don't have any method to deselect the  target entity so once chosen, the relation could never be changed anymore to anything else but what that target type allows. Sure, this could be helped by adding a deselection feature but isn't that a bit cumbersome? For example when editing an existing relationship, in order to change the relation, I would have to deselect the target entity first. Also, it seems that the use case for this feature is relatively rare (in comparison to #41). @bitno, what do you think?

**Comment by bitno** [comment]
I aknowledge, that this particular use case might be rarer than the one described in #41 . However, for some users, this might be a preferred way of editing/adding relations. I recognize the problem of deselecting a target entity, but this particular feature should be added anyway. It could be as simple as another click on the same entity, meaning one click to select and another one to deselect. Why do you, @moritzschepp , think it might be cumbersome? 
This brings me to another desired feature: being able to select more than one target. This could enhance the workflow, especially if the user is working on a particular batch of items, which all belong together. With "last created", he could easily create several relations at once.
@moritzschepp let me know your thoughts on this.

**Comment by moritzschepp** [comment]
Yes that makes sense. I was thinking about "I want to change the relation type". This would potentially require that I change (or deselect) the target entity first. But while I'm writing this, I realize that this use case doesn't happen very often.

"More than one target" is a good idea but why don't we discuss it in another issue? We could then close this one (once the original problem is solved) and release KOR 2.0.0.

**Comment by bitno** [comment]
@moritzschepp sure, will create a separate ticket.
