### ISSUE TITLE
Asset caching seems broken

### ISSUE THREAD

**Issue by moritzschepp** [coneda/kor#66]
After updates, some browsers require the user to do a manual expiring of the browser cache, see for example #65 and #62

**Comment by bitno** [comment]
Dear @moritzschepp, this issue can't be fixed with a reset of the cache. The current master is deployed on kor3 and no browser is able to display assets correctly, even after complete cache resets.
Thanks for checking.
![bildschirmfoto 2016-05-26 um 18 03 37](https://cloud.githubusercontent.com/assets/15378927/15581457/ad9b4ee6-236c-11e6-901e-0a3673d955b0.png)

**Comment by moritzschepp** [comment]
I just deactivated the custom css by

    mv shared/data/custom.css shared/data/custom.css.old

and the install looks okay? If there are problems with the customized css, it will have to be corrected after upgrades because it is not part of the source code.

**Comment by bitno** [comment]
No, the deactivation didn't solve the issue. See screenshot.
![bildschirmfoto 2016-05-26 um 18 45 38](https://cloud.githubusercontent.com/assets/15378927/15582605/228ada8c-2372-11e6-91f8-66cb857926b4.png)

**Comment by moritzschepp** [comment]
Ah ok this is about the missing translations for the fields within the master data. This is fixed on your install and on github.
