### ISSUE TITLE
JSON API: Populate 'relationships' on entities query

### ISSUE THREAD

**Issue by anthon** [coneda/kor#69]
@moritzschepp I know we've discussed this before, but I no longer know what the consensus was;

When pulling a list of entities (`/entities.json?kind_id=<:id>`), would it be possible to "pad" the returned entities with their relationships? Something like the previous `/api/1.0/entities/<:id>/show_full`, but without the related entities attached:

```
{
    uuid: ...
    id: ...
    name: ...
    relationships: [
        {
            created_at: ...
            from_id: <:from_id>
            id: <:id>
            lock_version: 0
            owner_id: null
            properties: []
            relation_id: <:rel_id>
            to_id: <:to_id>
            updated_at: ...
            uuid: ...
        },
        {
            ...
        }
    ]
    ...
}
```

The aim in the long run is probably to be able to render complex tree structures directly from the JSON API, but for now, a padding like that would solve a lot of problems. For example, to render a tree you would only need one query, and map it all up on the client.

**Comment by moritzschepp** [comment]
What would you expect the api to return when there are many (let's say 2000) relationships?

**Comment by anthon** [comment]
Same as `/show_full` used to do. But I'm not seeing that more in the routes, so I guess that was considered too much of a hack?

The way I see it it should be completely possible to list all relationships for an entity, but it should only be enabled with a flag, like `?include_relationships=true` or similar. That could then be enabled on all entity routes (`/component_search`). Default entity pagination is set to 10, and on the off-chance that an entity has 2000+ relationships, the front-end developer would have all the possibilities to keep the payload size down.

What do you think?

**Comment by moritzschepp** [comment]
So the problem with /show_full was that it did show the relationships but since there are often more than 10, it just gave the first 10. Afterwards we had to pull the rest with additional ajax requests anyhow. This is why we migrated to using just relation_counts which made the entity loading much faster but required loading of relationships separately by relation.

Doing long running requests like rendering a lot of data at a time is very inconvenient for the server: It stalls one CPU entirely for the duration of the request. While I can see that making more requests from a frontend point of view is inconvenient, it does allow for valuable "breaks". This is also more often the case than you might think: If we'd allow limitless rendering of relationships for a list of 10 entities then its enough if each has 50 relationships: The result of 500 brings already the above problems.

That said, I can embed a paginated result within the entity JSON which spares you the first request but everything beyond 10 relationships, you would have to pull separately. Its questionable though if that makes things easier for you: It basically depends on your data having a lesser degree than 10 so that you wouldn't have to implement code to pull more. But I'm happy to integrate it if you say it helps.

Actually, I'm currently working on the flags that you mentioned. For now, I have done this for datings, technical info, users, groups and such but I still need a bit of time.

**Comment by anthon** [comment]
> That said, I can embed a paginated result within the entity JSON which spares you the first request but everything beyond 10 relationships, you would have to pull separately. Its questionable though if that makes things easier for you: It basically depends on your data having a lesser degree than 10 so that you wouldn't have to implement code to pull more. But I'm happy to integrate it if you say it helps.

No, you're right, that wouldn't do much. For now then we'll just pull entities and `/directed_relationships` separately, and consolidate the results, reducing the amount of requests to 2 instead of <number_of_entities>.

**Comment by moritzschepp** [comment]
Now I know that github doesn't close issues the way I thought it would ;)

Anyhow, please have a look at the docs since I also changed the url for the relationships endpoint.
