### ISSUE TITLE
JSON API: Populating Medium on entities query (medium_id?)

### ISSUE THREAD

**Issue by anthon** [coneda/kor#70]
Right now, the only way to pull any attached medium is to separately query the entity. That means entity list queries can only be rendered as lists of text.

Since we don't want to kill the server (#69), it makes sense if only one medium per entity would be attached, per flag `?include_media=true` or similar. It could simply be the first attached medium, or one specified on the flag: `?include_media=<:medium_id>/<:medium_name>`

Is this already in the works, or what is the `medium_id: null` attribute on returned entries?

**Comment by moritzschepp** [comment]
So the media entities are just the same as other entities but since they include a reference to an (internal) table where the actual file-related stuff is stored (size, type, hash, etc). This is where medium_id points to. Since it relates the entity to a (single) file, its also needed to generate the url to that file and its representations. So an entity either IS an image or it is related to other entities that ARE images. So the query you are suggesting, would look like this: `ìnclude_media=<entity_id>`. That could be done but are you sure this is of any use to you without selecting for the relation type?

What is `medium_name` in `?include_media=<:medium_id>/<:medium_name>`?

**Comment by anthon** [comment]
So the medium_id is only of relevance if the entity is in fact of kind Medium? I see.

> ...are you sure this is of any use to you without selecting for the relation type?

Well, what I'm looking for is a way to attach some kind of representational image to a list of entities, for easy preview. Getting a list of entities and then having to make one additional call per entity just to get the URL for a thumbnail is a bit crazy. You're right, the `medium_id`/`medium_name` should probably be `relation_id`/`relation_name`, like a shortcut for the `/directed_relationship`. But I don't know if that's too messy.

Do you see the point? What would you suggest?

**Comment by anthon** [comment]
Hang on – `/component_search` is already catering to this problem, right?

**Comment by moritzschepp** [comment]
Yes `/component_search` does what you want .. to an extent, see also https://github.com/coneda/kor/issues/72#issuecomment-223053995

**Comment by anthon** [comment]
Ok, so `/component_search` comes very close, but the point is really to be able to show previews with query results. Right now, the `/component_search` output is tailored for the KOR admin interface, which only needs 4 very low-res images to get an idea of what's behind an entity. For any kind of public front-end, however, it would be really good to tune the included URLs a little:

- Either being able to choose which image is the first one (#73) or choose which media relation is being used to fill the `images: [...]` array.
- Including higher-res image URLs (not original, perhaps, but at least 'preview' size).
