### ISSUE TITLE
failed deployment of current master due to npm

### ISSUE THREAD

**Issue by bitno** [coneda/kor#96]
Dear @moritzschepp, I've just tried deploying the current master from an older 2.0 version and got this error:

> \e[0;34mkor@conedakor4.ethz.ch\e[0m: \e[1;34mcd /var/www/rack/kor/releases/20160925135043 ; RAILS_ENV=production bundle exec bin/kor secrets\e[0m
> \e[0;34mlocally\e[0m: \e[1;34mnpm run build\e[0m
> bash: npm: command not found
> \e[0;31mdeployment failed with status code 127\e[0m
> gta-institut-m-87:kor.git lzorc$ 

I suspect, this might be down to node.js missing, but even after installing it, I got the same error back.

Many thanks for your help on this and lots of greetings
Leo

**Comment by moritzschepp** [comment]
Yes, npm is needed to compile the widget code but that should actually not be required on deployment. I will fix that in the future.

As a workaround, installing nodejs should have worked since it includes npm. Is it possible that your shell is still using the old env vars? In that case, closing and re-opening the terminal app should make npm available.

**Comment by bitno** [comment]
Many thanks @moritzschepp, indeed the installation of node did make the instance available, even though the deployment failed. I just wanted to raise the issue. 
I'll also try your env vars suggestion, hopefully this will solve the deployment fail.
Thanks a lot, as always!

**Comment by moritzschepp** [comment]
No problem and thanks for the report!

However, the deployment was not completely finished, I'm sure. For example, the app should not have restarted since that is only done after the failing call to npm.

I also have to correct what I said earlier: npm will be needed to deploy. Its the only way to guarantee that the assets are compatible with the server code.

I close here but don't hesitate to re-open, should you disagree.
